spring:
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
