server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_db
    username: postgres
    password: newpassword

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka/
